export const adminConsoleCopy = {
  shell: {
    sectionLabel: "Municipal operations",
    title: "CityPulse admin console",
    description:
      "A decision-oriented workspace for moderation, prioritization, support operations, and geographic intelligence.",
    publicView: "Public view",
    citizenView: "Citizen view",
    navigationLabel: "Admin navigation",
    mobileNavigationLabel: "Admin mobile navigation",
    sections: {
      dashboard: "Dashboard",
      issues: "Issues",
      moderation: "Moderation",
      tickets: "Tickets",
      users: "Users",
      heatmap: "Heatmap",
    },
  },
  common: {
    adminOnly: "An administrator account is required to access this console.",
    loading: "Loading admin data",
    refresh: "Refresh",
    filterCategory: "Category",
    filterStatus: "Status",
    filterModeration: "Moderation state",
    filterTicketType: "Ticket type",
    filterPeriod: "Time range",
    filterScore: "Minimum importance",
    filterAll: "All",
    locationLabel: "Location",
    requesterLabel: "Requester",
    linkedIssueLabel: "Linked issue",
    createdLabel: "Created",
    actionPending: "Saving",
    noSelection: "Select a record to inspect more detail.",
    openIssue: "Open issue",
    openTicket: "Open ticket",
    openUser: "Open user",
    backToDashboard: "Back to dashboard",
    backToIssues: "Back to issues",
    backToTickets: "Back to tickets",
    backToUsers: "Back to users",
    active: "Active",
    banned: "Banned",
    internalNote: "Internal note",
    externalReply: "Visible reply",
    resolve: "Resolve",
    queued: "Queued",
    published: "Published",
    archived: "Archived",
    approved: "Approved",
    rejected: "Rejected",
    manualReview: "Manual review",
    low: "Low",
    medium: "Medium",
    high: "High",
    support: "Support",
    skip: "Skip",
    moreLikeThis: "More like this",
    lessLikeThis: "Less like this",
    signal: "Signal",
    rawValue: "Raw value",
    details: "Details",
    appeals: "Appeals",
    yes: "Yes",
    no: "No",
    noData: "No data available yet.",
    successSaved: "Update saved.",
  },
  dashboard: {
    eyebrow: "Operations overview",
    title: "Cross-functional civic response view",
    description:
      "Track issue flow, moderation throughput, priority concentrations, trust conditions, and support load from one surface.",
    cards: {
      totalIssues: "Total issues",
      newThisWeek: "New this week",
      published: "Published",
      pending: "Pending moderation",
      averageTrust: "Average trust",
      highAbuse: "High abuse risk",
      ticketQueue: "Open ticket queue",
      supportActions: "Support reactions",
    },
    charts: {
      activityTitle: "Operational activity trend",
      activityBody:
        "Issue intake, support actions, and ticket creation over recent weeks.",
      supportTitle: "Reaction mix",
      supportBody:
        "Signals that influence ranking, recommendation quality, and abuse detection.",
      impactTitle: "Impact score distribution",
      impactBody:
        "Public importance scores are clustered so operators can see how much of the queue sits in each range.",
      moderationTitle: "Moderation outcomes",
      trustTitle: "Trust distribution",
      duplicateTitle: "Duplicate concentration",
      topAreasTitle: "Top impacted areas",
      topAreasBody:
        "Geographic cells where pain points accumulate with high issue density or score concentration.",
      topPriorityTitle: "Top priority issues",
      topPriorityBody:
        "Highest-ranked issues based on trust-weighted support, duplicates, and impact signals.",
      recentTicketsTitle: "Recent ticket queue",
      recentModerationTitle: "Recent moderation outcomes",
      heatmapPreviewTitle: "Spatial pressure preview",
      heatmapPreviewBody:
        "A lightweight spatial summary of current urban pain points before deeper heatmap analysis.",
    },
  },
  issues: {
    eyebrow: "Issue operations",
    title: "Inspect and operate on issue records",
    description:
      "Review public impact, moderation, duplicate relationships, attachments, and manual publishing actions.",
    emptyTitle: "No issues match the current filters",
    emptyBody:
      "Adjust the filter shell or wait for new reports to move through the system.",
    listTitle: "Issue queue",
    detailTitle: "Issue detail",
    supportMetricsTitle: "Support and weighting",
    impactTitle: "Impact breakdown",
    moderationTitle: "Moderation results",
    attachmentsTitle: "Attachments",
    duplicatesTitle: "Duplicate relationships",
    actionsTitle: "Manual actions",
    auditTitle: "Admin audit trail",
    publishAction: "Publish",
    approveAction: "Approve",
    rejectAction: "Reject",
    archiveAction: "Archive",
    reopenAction: "Reopen",
    bypassAiLabel: "Bypass AI rationale",
    noteLabel: "Operator note",
    duplicateLinkTitle: "Link duplicate to canonical issue",
    canonicalIssueLabel: "Canonical issue ID",
    archiveDuplicateLabel: "Archive the duplicate after linking",
    similarityLabel: "Similarity score",
    distanceLabel: "Distance (km)",
    textSimilarityLabel: "Text similarity",
    categoryMatchLabel: "Category match",
    reasonLabel: "Reason summary",
    linkDuplicateAction: "Link duplicate",
    noAttachments: "No attachments were added to this issue.",
    noDuplicates: "No duplicate relationships recorded yet.",
    noActions: "No admin actions recorded for this issue yet.",
  },
  tickets: {
    eyebrow: "Tickets and appeals",
    title: "Resolve user support and appeal workflows",
    description:
      "Handle issue-linked appeals, product feedback, and operational follow-up from a threaded queue.",
    emptyTitle: "No tickets match the current filters",
    emptyBody:
      "The queue is clear for the selected filters. Broaden the scope to inspect historical items.",
    listTitle: "Ticket queue",
    detailTitle: "Ticket thread",
    messageLabel: "Reply",
    internalLabel: "Internal note only",
    statusLabel: "Update status",
    sendReply: "Send reply",
    applyStatus: "Apply status",
    issueContextTitle: "Linked issue context",
    messagesTitle: "Conversation",
    noMessages: "No ticket messages yet.",
  },
  users: {
    eyebrow: "User operations",
    title: "Trust, abuse, and participation oversight",
    description:
      "Inspect hidden trust scoring, abuse risk, reporting history, moderation exposure, and account actions.",
    emptyTitle: "No users available",
    emptyBody:
      "User integrity records will appear as participation data accumulates.",
    listTitle: "User watchlist",
    profileTitle: "User profile",
    trustFactorsTitle: "Trust factors",
    abuseFactorsTitle: "Abuse factors",
    moderationHistoryTitle: "Moderation history",
    submissionsTitle: "Recent submissions",
    reactionsTitle: "Reaction patterns",
    ticketsTitle: "Recent tickets",
    metricsTitle: "Integrity metrics",
    eventsTitle: "Recent integrity events",
    recommendedActionsTitle: "Recommended actions",
    trustScoreLabel: "Trust score",
    abuseRiskLabel: "Abuse risk",
    emailLabel: "Email",
    localeLabel: "Locale",
    activeLabel: "Active",
    lastLoginLabel: "Last login",
    banAction: "Ban user",
    unbanAction: "Unban user",
    noteLabel: "Action note",
    emptyHistory: "No records yet for this section.",
  },
  heatmap: {
    eyebrow: "Geographic intelligence",
    title: "Spatial pain-point analysis",
    description:
      "Use category, lifecycle, moderation, and score filters to understand where urban issues concentrate.",
    publicTitle: "City issue heatmap",
    publicDescription:
      "A lightweight public-facing spatial view of current city signals without exposing internal moderation or trust metrics.",
    previewTitle: "Heatmap detail",
    previewBody:
      "Select a cell to inspect weighted activity, duplicates, category dominance, and concentration details.",
    filtersTitle: "Heatmap filters",
    noPointsTitle: "No heatmap cells match the current filters",
    noPointsBody:
      "Broaden the selected date range or lower the minimum score threshold to explore more of the city.",
    trustWeightedActivity: "Trust-weighted activity",
    duplicateCount: "Duplicate clusters",
    needsReviewCount: "Needs review",
    issueCount: "Issues",
    topCategory: "Top category",
    averageImpact: "Average importance",
  },
} as const;
