export const appCopy = {
  header: {
    brandTagline: "Civic signal platform",
    publicHome: "Home",
    publicList: "Issue list",
    publicMap: "Issue map",
    discover: "Discover",
    create: "Report issue",
    myIssues: "My issues",
    dashboard: "Overview",
    signIn: "Sign in",
    signOut: "Sign out",
    citizenPanel: "Citizen panel",
    adminPanel: "Admin panel",
    signedInAs: "Signed in as",
    themeToggle: "Toggle color theme",
  },
  footer: {
    description: "Monorepo scaffold for civic reporting, moderation, and operations.",
    readiness: "Prepared for multilingual, AI-assisted, and role-separated product growth.",
  },
  auth: {
    title: "Citizen access",
    subtitle:
      "Sign in to support issues, submit reports, and track the status of your own cases.",
    signInTitle: "Sign in",
    registerTitle: "Create account",
    emailLabel: "Email",
    passwordLabel: "Password",
    fullNameLabel: "Full name",
    localeLabel: "Preferred locale",
    signInAction: "Sign in",
    registerAction: "Create account",
    switchToRegister: "Need an account?",
    switchToSignIn: "Already have an account?",
    registrationSuccess:
      "Account created. Sign in with the credentials you just registered.",
    helper:
      "Authentication stays local to this browser session until a dedicated app auth flow is added.",
    requiredTitle: "Citizen sign-in required",
    requiredBody:
      "This action needs an authenticated citizen account. You can still browse public issues without signing in.",
    goToAuth: "Open sign-in",
  },
  citizenShell: {
    eyebrow: "Citizen workspace",
    title: "Discovery, reporting, and follow-up in one place",
    description:
      "Browse public issues, submit a better report, and keep track of your own cases from one place.",
    dashboard: "Overview",
    discover: "Swipe feed",
    create: "Create issue",
    myIssues: "My issues",
    publicIssues: "Public issues",
    backToPublic: "Public issues",
    mobileNavigation: "Citizen navigation",
  },
  dashboard: {
    eyebrow: "Citizen tools",
    title: "Choose how you want to contribute today",
    description:
      "CityPulse separates discovery, reporting, and follow-up so the workflow feels focused on both mobile and desktop.",
    cards: [
      {
        title: "Discover priority issues",
        description:
          "Use the swipe feed to support relevant issues and shape what should surface next.",
        cta: "Open swipe feed",
      },
      {
        title: "Report a new issue",
        description:
          "Submit a clear report with location context, photos, duplicate guidance, and an optional constructive rewrite.",
        cta: "Open create flow",
      },
      {
        title: "Track your reports",
        description:
          "Review your submitted issues, their current status, and attached evidence in one consistent list.",
        cta: "Open my issues",
      },
    ],
    highlights: [
      "Mobile-first swipe feedback with explicit controls and public detail access.",
      "Constructive reporting flow with duplicate checks and an optional rewrite assist.",
      "Consistent public list, map, and personal issue tracking surfaces.",
    ],
  },
  issueViews: {
    title: "Public issues",
    subtitle:
      "Browse published civic issues with a consistent map, list, and details experience.",
    listTab: "List",
    mapTab: "Map",
    sortTop: "Top",
    sortRecent: "Recent",
    sortNearby: "Nearby",
    allCategories: "All categories",
    statusLabel: "Status",
    publishedOnly: "Published",
    categoryLabel: "Category",
    sortLabel: "Sort",
    useMyLocation: "Use my location",
    loadingTitle: "Loading public issues",
    emptyTitle: "No public issues to show yet",
    emptyBody:
      "Published issues will appear here once they clear moderation and are made visible to citizens.",
    errorTitle: "Unable to load public issues",
    retry: "Retry",
    openDetails: "Open details",
    openPage: "Open full page",
    supportCountLabel: "supporters",
    noImage: "No image",
    detailBack: "Back to public issues",
    detailMeta: "Public issue detail",
    mapEyebrow: "Map view",
    listEyebrow: "List view",
    nearbyHint:
      "Nearby sorting becomes more useful once device location is available. You can still browse all published issues without it.",
    mapPanelTitle: "Published issues on the map",
    mapPanelBody:
      "Markers show only public issues. Open a marker to review details before switching to the full issue page.",
  },
  issueDetail: {
    title: "Issue details",
    locationTitle: "Location",
    metadataTitle: "Issue metadata",
    supportAction: "Support this issue",
    close: "Close details",
    viewPage: "Open full page",
    attachmentsTitle: "Attachments",
    localeLabel: "Source locale",
    createdLabel: "Created",
    updatedLabel: "Updated",
    coordinatesLabel: "Coordinates",
  },
  discover: {
    title: "Swipe through public issues",
    subtitle:
      "Support what matters, skip what is not relevant, and teach future recommendations without exposing admin-only analytics.",
    support: "Support this issue",
    skip: "Skip",
    moreLikeThis: "Show more like this",
    lessLikeThis: "Show less like this",
    details: "View details",
    refresh: "Refresh feed",
    refreshed: "Feed refreshed",
    stackTitle: "Current civic feed",
    stackBody:
      "Each card represents a published issue. Swiping or using explicit controls shapes future ranking signals without blocking full issue review.",
    deckEmptyTitle: "You have reached the end of the current feed",
    deckEmptyBody:
      "Refresh the feed or switch to the public list if you want a broader view of published issues.",
    noAuthBody:
      "You can browse the feed without signing in, but feedback actions will only be saved for authenticated citizens.",
    savedAction: "Feedback saved.",
    localActionOnly: "Feedback applied locally. Sign in to save it to your account.",
  },
  create: {
    title: "Create a clear civic report",
    subtitle:
      "Guide the report through content, location, and review so submission stays precise and constructive.",
    stepContent: "Content",
    stepLocation: "Location",
    stepReview: "Review",
    titleLabel: "Short title",
    titlePlaceholder: "Describe the issue in one short line",
    descriptionLabel: "Description",
    descriptionPlaceholder:
      "Explain what is happening, where it is happening, and why it matters for residents.",
    categoryLabel: "Category",
    categoryPlaceholder: "Select a category",
    photoLabel: "Photos",
    photoHint:
      "This commit stores upload metadata and local previews so storage delivery can be plugged in later without changing the form.",
    photoAction: "Add photos",
    photoEmpty: "No photos selected yet.",
    removePhoto: "Remove photo",
    rewriteAction: "Rewrite constructively",
    rewriteHeading: "Constructive rewrite suggestion",
    rewriteBody:
      "This optional assistive pass keeps the meaning but makes the report easier to route and review.",
    acceptRewrite: "Use rewrite",
    rejectRewrite: "Keep original",
    rewriteNoChanges: "The rewrite assist works best once both title and description are filled in.",
    locationHeading: "Pick the location",
    locationBody:
      "Click on the map or use your device location to anchor the report. Precise coordinates improve duplicate detection.",
    useMyLocation: "Use my location",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    reviewHeading: "Review before submit",
    reviewBody:
      "CityPulse checks for likely duplicates before submission and lets you support an existing issue when that is the better path.",
    submissionSummary: "Submission summary",
    duplicateHeading: "Possible duplicate issues",
    duplicateBody:
      "These look related. You can support an existing issue or continue with your own report if it adds distinct information.",
    noDuplicates: "No close duplicates were found in the current public and moderation-ready pool.",
    checkDuplicates: "Check duplicates",
    supportExisting: "Support existing issue",
    submitAnyway: "Submit anyway",
    submit: "Submit issue",
    next: "Continue",
    back: "Back",
    createAnother: "Create another issue",
    successTitle: "Issue submitted",
    successBody:
      "Your issue has been sent for moderation. You can now review it in your personal issue list.",
    goToMyIssues: "Open my issues",
    validationTitle: "Please finish the required fields",
    duplicateSupportSaved:
      "Support for the existing issue has been recorded. You can still submit if your report adds distinct evidence.",
    rewriteSaved: "Rewrite applied to the draft.",
    locationError: "Location access is unavailable on this device or was denied.",
    metadataPending:
      "Photos are attached as metadata placeholders in this commit so storage upload can be integrated without reworking the flow.",
  },
  myIssues: {
    title: "My issues",
    subtitle:
      "Review the issues you have submitted, their current status, and the evidence attached so far.",
    emptyTitle: "You have not submitted any issues yet",
    emptyBody:
      "When you create your first issue, it will appear here with its moderation and visibility status.",
    createAction: "Create an issue",
    supportLabel: "support",
    draftLabel: "Your submitted reports",
  },
  common: {
    loading: "Loading",
    coordinates: "Coordinates",
    attachments: "Attachments",
    sourceLocale: "Locale",
    createdAt: "Created",
    updatedAt: "Updated",
    status: "Status",
    category: "Category",
    location: "Location",
    close: "Close",
    retry: "Retry",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    overview: "Overview",
    open: "Open",
    none: "None",
  },
} as const;
